#!/bin/bash
cd "/home/linaro/autovip"
LOG_PATH=logs/stderr

ts=$(stat -c '%Y' data.ini)
sleep 5
current_ts=$(stat -c '%Y' data.ini)
while ((current_ts == ts))
do
	echo "heartbeat_checker: waiting for the program to start.">>$LOG_PATH
	sleep 5
	current_ts=$(stat -c '%Y' data.ini)
done
current_time=$(date "+%Y.%m.%d-%H.%M.%S")
echo "heartbeat_checker: started listening to heartbeat. $current_time">>$LOG_PATH
while :
do
	ts=$(stat -c '%Y' data.ini)
	sleep 10
	current_ts=$(stat -c '%Y' data.ini)
	if ((current_ts == ts)); then
		echo "heartbeat_checker: detected no heartbeat, restarting the device. last timestamp: $current_ts">>$LOG_PATH
		break
	fi
done
/sbin/shutdown -r now >>$LOG_PATH
echo "shutdown command executed...">>$LOG_PATH
